name: oauth_interceptor
description: Oven-ready Dio interceptor for handling OAuth 2.0
version: 1.0.0
repository: https://github.com/netsells/oauth_interceptor

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  clock: ^1.1.0
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_secure_storage: ^5.0.2
  time: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  netsells_flutter_analysis: ^3.0.0
