name: oauth_interceptor
description: Oven-ready Dio interceptor for handling OAuth 2.0
version: 1.3.0
repository: https://github.com/netsells/oauth_interceptor

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  clock: ^1.1.1
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_secure_storage: ^6.0.0
  time: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  netsells_flutter_analysis: ^3.2.0
