name: oauth_interceptor
description: Oven-ready Dio interceptor for handling OAuth 2.0
version: 2.0.1
repository: https://github.com/netsells/oauth_interceptor

environment:
  sdk: ">=2.17.6 <4.0.0"
  flutter: ">=3.7.0"

dependencies:
  clock: ^1.1.1
  dio: ^5.1.2
  flutter:
    sdk: flutter
  flutter_secure_storage: ^8.0.0
  time: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  netsells_flutter_analysis: ^4.0.0
