name: oauth_interceptor
description: Oven-ready Dio interceptor for handling OAuth 2.0
version: 2.2.0
repository: https://github.com/netsells/oauth_interceptor

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  clock: ^1.1.1
  dio: ^5.1.2
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  time: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  http_mock_adapter: ^0.6.1
  mocktail: ^1.0.4
  netsells_flutter_analysis: ^5.0.0
